@user = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJyb2xlIjoidXNlcnMiLCJleHAiOjE2NTY1OTQ1MzF9.pUuR19wspGDXa9-mhUrOCkezUjYr388RZHuAlkekY5Y

@admin = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IiIsImV4cCI6MTY1NjU2MDEwM30.pLorDxRYggggJhOwYKljkag2Cx_NqhnIfWiPzEusOLY

### GET DATA
GET http://localhost:8080/product HTTP/1.1
Authorization: {{user}}

### GET DATA ByID
GET http://localhost:8080/product/2 HTTP/1.1
Authorization: {{user}}

### SAVE
POST http://localhost:8080/product HTTP/1.1
Content-Type: application/json
Authorization: {{user}}

{
    "name": "Nescafe latte",
    "price": "10000",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex ipsa libero, repellendus eum similique dolorem. Rem sequi, beatae expedita ab cumque maxime nam voluptate nesciunt atque animi reprehenderit quos culpa!",
    "image": "https://res.cloudinary.com/devops2/image/upload/v1656413859/products/Nescafe-RTD-Latte-240ml_n2yypt.jpg"
}

### get Users
GET http://localhost:8080/users/all HTTP/1.1
Content-Type: application/json
Authorization: {{user}}

### Create data Users
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "username" : "user",
    "password" : "abcd12345",
    "role": "users"
}

### Loginn
POST http://localhost:8080/auth HTTP/1.1
Content-Type: application/json

{
    "username" : "user",
    "password" : "abcd12345"
}
